POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "Nelson Mandela",
    "number": "111-222-333"
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "John Doe",
    "number": "44-12343254"
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "Timmy"
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "number": "111-222-333"
}