POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "Nelson Mandela",
    "number": "111-222-333"
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "John Doe",
    "number": "44-123432545"
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "Timmy"
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "number": "111-222-333"
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
      "name": "Arto Hellas",
      "number": "040-123456",
      "id": 1
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "39-44-5323523",
    "id": 2
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": "12-43-234345",
    "id": 3
}
###
POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "Mary Poppendieck",
    "number": "39-23-6423122",
    "id": 4
}