DELETE http://localhost:3000/api/persons/1
###
DELETE http://localhost:3000/api/persons/2
###
DELETE http://localhost:3000/api/persons/3
###
DELETE http://localhost:3000/api/persons/4
###
DELETE http://localhost:3000/api/persons/65905660bbf4b4db5a6d23d0